spring:
  profiles.active: default
  redis:
    url:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/h2/app_db;
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: none


server:
  port: 8180
logging:
  level:
    org.springframework.web: 'DEBUG'

